# Generated by Django 3.0.2 on 2020-06-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_at', models.DateTimeField()),
                ('registered_by', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
