# Generated by Django 3.0.2 on 2020-06-28 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level_price', models.CharField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'High')], default='', max_length=1)),
                ('registered_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('option', models.CharField(choices=[(1, 'Female'), (2, 'Male'), (3, 'Kids'), (4, 'Bedroom'), (5, 'Kitchen'), (6, 'Bathroom')], default='', max_length=255)),
                ('registered_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('S', 'Short'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registered_by', models.CharField(max_length=255)),
                ('registered_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
